= Upgrade Guide
:toc: macro

This document describes steps necessary to upgrade 21-points.com on Heroku. It's contains the lessons learned in link:https://www.jhipster-book.com/#!/news/entry/upgrading-21-points-health-from-v1-to-v4[upgrading from version 1 to 4], link:https://www.jhipster-book.com/#!/news/entry/21-points-v5-has-been-released[version 4 to 5], and version 5 to 7.

toc::[]

== Copy production database locally

. To export the production database to a local database, use the `pg:pull` command:
+
[source,shell]
----
heroku pg:pull HEROKU_POSTGRESQL_SILVER_URL health --app health-by-points
----
+
This command will create a local database called `health` and populate it with the data from the production database.
+
TIP: See https://devcenter.heroku.com/articles/heroku-postgres-import-export[Heroku's import/export docs for PostgreSQL] if you need additional information.

. Then, log in to the database and run the following commands to fix the data:
+
[source,shell]
----
psql health
\dt;
reassign owned by mraible to twentyonepoints;
update databasechangelog set md5sum=null;
delete from databasechangeloglock;
----

. https://www.liquibase.com/download[Download Liquibase] and installed it in `/opt/tools`. I ran the following command to copy the PostgreSQL JDBC driver from my local Maven repo to Liquibase's classpath.
+
[source,shell]
----
cp ~/.m2/repository/org/postgresql/postgresql/42.2.19/postgresql-42.2.19.jar lib/.
----

. Run Liquibase to generate an XML changelog for the differences between the two databases.
+
[source,shell]
----
./liquibase \
  --driver=org.postgresql.Driver --url=jdbc:postgresql://localhost:5432/health \
  --username=postgres diffChangeLog \
  --referenceUrl=jdbc:postgresql://localhost:5432/twentyonepoints \
  --referenceUsername=twentyonepoints --referencePassword=21points \
  --changelog-file=migrate_from_v5.xml
----

. Copy the results to `src/main/resources/config/liquibase/changelog` and add a reference to it in `src/main/resources/config/liquibase/master.xml`.

. Update `application-prod.xml` to point to the `health` database you downloaded from Heroku.

. Run `./gradlew bootRun -Pprod`, log in, and browse the app. Update Liquibase migration script as necessary.

== Migrate from Bansai to Elastic Cloud

On Heroku, the https://elements.heroku.com/addons/bonsai[Bonsai Elasticsearch] is configured as an add-on. JHipster is automatically configured to talk to it.

Unfortunately, as of JHipster 7.9.3, Elasticsearch https://github.com/jhipster/generator-jhipster/issues/20315[doesn't work out of the box with Heroku]. To solve this, you can create a Docker image with Elasticsearch and deploy it to somewhere that can run it, or you can use Elastic Cloud.

I chose to https://www.jhipster.tech/using-elasticsearch/#using-elastic-cloud[use Elastic Cloud].

Then, I installed the https://github.com/Ebsan/generator-jhipster-es-entity-reindexer[JHipster Elasticsearch Reindexer module] and https://github.com/Ebsan/generator-jhipster-es-entity-reindexer/pull/8/files[fixed some imports for JHipster 7.9.3].

I enabled it in `application.yml`:

[source,yml]
----
application:
  elasticsearch:
    reindex-on-startup: true
----

== Deploy to Heroku

. Use Heroku's Dashboard to turn on maintenance mode.

. Change the version number in `package.json` and `build.gradle` and commit the changes.

. Enable the service worker in `app.module.ts` for PWA support in production.

. Push the changes to GitHub and do a release.

. Run the `heroku-deploy.sh` script, and start everything back up.

. Turn off the reindexer after the first deploy.

  heroku config:set APPLICATION_ELASTIC_SEARCH_REINDEX-ON-STARTUP=false

. Disable the service worker in `app.module.ts`, update the versions in `package.json` and `build.gradle`, then commit and push.
